apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "charts.fullname" . }}-backend-viewer
  labels:
    {{- include "charts.labels" . | nindent 4 }}
rules:
  - apiGroups: ["keda.sh"]
    resources: ["scaledobjects"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "charts.fullname" . }}-backend-viewer
  labels:
    {{- include "charts.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "charts.fullname" . }}-backend
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "charts.fullname" . }}-backend-viewer
  apiGroup: rbac.authorization.k8s.io
