apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  ports:
  - port: {{ .Values.mongodb.service.port }}
    targetPort: 27017
  selector:
    app: mongodb
    release: {{ .Release.Name }}
