frontend:
  image: keda-frontend
  tag: latest
  replicas: 1
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    host: "keda.yourdomain.com"

backend:
  image: keda-backend
  tag: latest
  replicas: 1
  service:
    type: ClusterIP
    port: 8001
  env:
    MONGO_URL: "mongodb://mongodb:27017"
    DB_NAME: "keda_db"
    CORS_ORIGINS: "*"

mongodb:
  image: mongo
  tag: "7.0"
  persistence:
    enabled: true
    size: 1Gi
  service:
    port: 27017
